version: "2.1"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
    networks:
      - hackathon

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka-socket:/var/run/docker.sock
    networks:
      - hackathon

  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    ports:
      - 6123:6123
      - 8081:8081
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - hackathon

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - 6121
      - 6122
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
      - "zeppelin:zeppelin"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - hackathon

  zeppelin:
    image: dataramblers/zeppelin-arch:latest
    ports:
      - 8080:8080
    networks:
      - hackathon
    volumes:
      - zeppelin-notebooks:/zeppelin/notebook
      - zeppelin-conf:/zeppelin/conf
      - zeppelin-localrepo:/zeppelin/local-repo

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#       nofile:  # Only ES v.5.2.2
#         soft: 65536
#         hard: 65536
    mem_limit: 1g
#     cap_add: # Only ES v.5.2.2
#       - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - hackathon

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
# nofile:  # Only ES v.5.2.2
#        soft: 65536
#        hard: 65536
    mem_limit: 1g
#    cap_add: # Only ES v.5.2.2
#      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
       - hackathon

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  zeppelin-notebooks:
    driver: local
  zeppelin-localrepo:
    driver: local
  zeppelin-conf:
    driver: local
  kafka-socket:
    driver: local

networks:
  hackathon:
